import Head from 'next/head';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.css';
import { Button } from '@mui/material';
import axios from 'axios';

const inter = Inter({ subsets: ['latin'] });

export default function Home({ data }: { data: any }) {
  return (
    <>
      <Head>
        <title>Movies</title>
        <meta name='description' content='Generated by Movies' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div style={{ display: 'flex', flexDirection: 'column' }}>
          <span>best planet: {data.name}</span>
          <span>orbital_period: {data.orbital_period}</span>
          <span>diameter: {data.diameter}</span>
          <span>climate: {data.climate}</span>
        </div>
        <Button variant='contained'>Movies Test</Button>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  try {
    const res = await axios.get('https://swapi.dev/api/planets/1');

    return {
      props: {
        data: res.data,
      },
    };
  } catch (error) {
    return {
      props: {
        error: 'Failed to fetch data.',
      },
    };
  }
}
